name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gofmt:
    name: Go Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Check Go formatting
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then
            echo "Go code is not formatted. Please run 'gofmt -s -w .'"
            gofmt -s -d .
            exit 1
          fi

  golangci-lint:
    name: Go Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=5m

  go-mod-tidy:
    name: Go Modules Tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Check if go.mod is tidy
        run: |
          go mod tidy
          if [ -n "$(git diff --name-only)" ]; then
            echo "go.mod is not tidy. Please run 'go mod tidy'"
            git diff
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Test
        run: go test -v -short ./...

  release-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - uses: anchore/sbom-action/download-syft@v0
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
      - name: Check release (dry-run)
        run: |
          goreleaser check
          goreleaser release --snapshot --clean --skip publish
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_ACCESS_TOKEN }}

  integration-test:
    runs-on: ubuntu-latest
    container:
      image: rootsdev/trellis-cli-dev
    steps:
      - run: go version
      - run: ansible --version
      - name: Trellis version
        run: git log -1 --format="%h %s %aD"
        working-directory: /test/dummy/trellis
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - uses: actions/cache@v5
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Tests
        run: make test RUN=
      - name: Store artifacts
        uses: actions/upload-artifact@v6
        with:
          name: trellis-cli
          path: /test/trellis-cli
